Replace packet-infra Helm chart with native Go templates
gardener/gardener-extension-provider-packet pull request #139
Opened 2021-05-21 07:45 UTC by rfranzke

**How to categorize this PR?**

/area open-source
/kind cleanup
/platform packet

**What this PR does / why we need it**:
In order to prepare for Helm 3 and to go in line with gardener/gardener#2754, the `packet-infra` Helm chart is eliminated and replaced with native Golang templates.
On the way, I updated the dependencies.

**Special notes for your reviewer**:
See discussion in https://github.com/gardener/gardener/pull/3994#pullrequestreview-652016478 ff.

**Release note**:

```other operator
NONE
```

2021-05-21 07:52 UTC, vpnachev commented
Needs `make generate`.

2021-05-21 10:51 UTC, timebertt requested changes

2021-05-21 10:51 UTC, timebertt commented on go.mod
> +	github.com/gardener/gardener v1.23.0
```suggestion
	github.com/gardener/gardener v1.23.1
```

in order to get https://github.com/gardener/gardener/pull/4089?

2021-05-21 10:51 UTC, timebertt commented on pkg/controller/infrastructure/templates/main.tpl.tf
> +  project_id = "{{ .Values.packet.projectID }}"
```suggestion
  name = "{{ .clusterName }}-ssh-publickey"
  public_key = "{{ .sshPublicKey }}"
  project_id = "{{ .packet.projectID }}"
```

Right? Same would apply in line 16.

2021-05-21 10:56 UTC, rfranzke commented on pkg/controller/infrastructure/templates/main.tpl.tf
> +  project_id = "{{ .Values.packet.projectID }}"
Nice catch... :) thanks!

2021-05-21 12:06 UTC, timebertt approved these changes
Thanks!
/lgtm
apart from
```
> Generate / Vendor Check
>> make generate
make generate needs to be run:
 M example/controller-registration.yaml
make: *** [Makefile:97: check-generate] Error 1
```

2021-05-21 13:00 UTC, rfranzke commented
Strange... I explicitly regenerated and my diff showed changes in `example/controller-registration.yaml`...

2021-05-21 13:08 UTC, rfranzke commented
OK, it seems the issue was helm v2 vs. v3... :)

2021-05-22 12:55 UTC, timebertt commented
> OK, it seems the issue was helm v2 vs. v3... :)

Yeah. That's what we're trying to get rid of 😄

2021-05-22 12:58 UTC, timebertt approved these changes
/lgtm

2021-05-22 12:59 UTC, merged